server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instancias
          uri: https://github.com/RagnarkLoth/microservicios-practica
          search-paths: config-data
  application:
    name: config-service

